name: Nodejs Hapi Template
on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master
jobs:
    build_and_test:
        name: Build & Test
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [14.x]
        steps:
            - uses: actions/checkout@v2
            - name: Install dependencies
              run: yarn
            - name: Lint
              run: yarn lint
            - name: Test
              run: yarn test
